language: java

jdk:
  - openjdk17
#  - openjdk8
#  - openjdk11

# no corpus testing on travis
script: "mvn -pl -xemph:corpus-testing verify"

after_success:
  - bash <(curl -s https://codecov.io/bash)
